### ISSUE TITLE
How to connect remote control ?

### ISSUE THREAD

**Issue by YuHanChen04** [ev3dev/ev3dev-lang-python#415]
Hey , I have a program want to ask you to help.
I want to define my Remote control and connect with my ev3dev .
I was use this  rc = ev3.RemoteControl(channel=1)
and sudo python3 myfile.py it shows this on the terminal ,
it make me feel so confuse , could you help me to solve program ?
I really really need your help . Thank you so much !!!

**Traceback (most recent call last):
  File "test.py", line 53, in <module>
    rc.process()
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 2648, in process
    new_state = set(self.buttons_pressed)
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 2810, in buttons_pressed
    return RemoteControl._BUTTON_VALUES.get(self._sensor.value(self._channel), [])
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 1758, in value
    self._value[n], value = self.get_attr_int(self._value[n], 'value'+str(n))
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 214, in get_attr_int
    attribute, value = self._get_attribute(attribute, name)
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 198, in _get_attribute
    raise Exception('Device is not connected')
Exception: Device is not connected**

**Comment by WasabiFan** [comment]
Please provide the details of the ev3dev and library versions you are using. Did you make sure to plug in the infrared sensor before running your code?

**Comment by YuHanChen04** [comment]
sorry , i have solved this program , cause I didn't define the number of the port!!

thanks so mush!!
