### ISSUE TITLE
NXT SoundSensor does not work

### ISSUE THREAD

**Issue by ensonic** [ev3dev/ev3dev-lang-python#435]
- **ev3dev version:** 4.4.47-19-ev3dev-ev3
- **ev3dev-lang-python version:** 1.0.0
btw. please edit the template and tell people to run: apt-cache show python3-ev3dev | grep Version

```
# nxt sound sensor connected to input port 1
from ev3dev import auto as ev3dev
s = ev3dev.SoundSensor(ev3dev.INPUT_1)
print(s.mode)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.8.1.post11-py3.4.egg/ev3dev/core.py", line 1677, in mode
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.8.1.post11-py3.4.egg/ev3dev/core.py", line 221, in get_attr_string
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.8.1.post11-py3.4.egg/ev3dev/core.py", line 198, in _get_attribute
Exception: Device is not connected
```

I found some old discussion here: https://github.com/ev3dev/ev3dev-lang/issues/59#issuecomment-96771309 - but that code does not work anymore. If there is anything the developer need to do to use these sensors, we need to document this.

The NXT LightSensor works out of the box though:
```
from ev3dev import auto as ev3dev
s = ev3dev.LightSensor(ev3dev.INPUT_1)
print(s.value())
155
```
and so does the NXT TourchSensor.

When I plug the NXT Sound sensor I get this in the syslog:
```
Dec 05 10:26:58 ev3dev kernel: lego-sensor sensor11: Registered 'nxt-analog' on 'in1'.
Dec 05 10:26:58 ev3dev kernel: lego-port port0: Added new device 'in1:nxt-analog'
```
When I do this with the NXT Light Sensor I get this:
```
Dec 05 10:27:24 ev3dev kernel: lego-sensor sensor12: Registered 'lego-nxt-light' on 'in1'.
Dec 05 10:27:24 ev3dev kernel: lego-port port0: Added new device 'in1:lego-nxt-light'
```

**Comment by ddemidov** [comment]
Would this work?
```py
import ev3dev.ev3 as ev3
from time import sleep

p = ev3.LegoPort(ev3.INPUT_1)
p.set_device = 'lego-nxt-sound'
sleep(1)
s = ev3.SoundSensor()
```

**Comment by ensonic** [comment]
Yes, That works! Will add it to the code in the robertalab hal. Thanks a lot.
Just tried 
```
echo "lego-nxt-sound" | sudo tee /sys/class/lego-port/port0/set_device 
```
and that makes it work too. Should we add the code you posted to the nxt-sensor setup.

**Comment by dwalton76** [comment]
@ensonic can you submit a PR for this? I do not have a NXT Sound Sensor to test with.

**Comment by ensonic** [comment]
Given the code:
https://github.com/ev3dev/ev3dev-lang-python/blob/develop/ev3dev/sensor/lego.py#L810
``` python
def __init__(self, address=None, name_pattern=SYSTEM_DEVICE_NAME_CONVENTION, name_exact=False, **kwargs):
    super(SoundSensor, self).__init__(address, name_pattern, name_exact, driver_name=['lego-nxt-sound'], **kwargs)
```
I am not sure what happens if one does not specify `address`. Do we try to *autodetect* the port? I would do a change like:
```python
def __init__(self, address=None, name_pattern=SYSTEM_DEVICE_NAME_CONVENTION, name_exact=False, **kwargs):
    if address:
        ev3dev.LegoPort(address).set_device = 'lego-nxt-sound'
    super(SoundSensor, self).__init__(address, name_pattern, name_exact, driver_name=['lego-nxt-sound'], **kwargs)
```
Note that the string is the same we set in the `driver_name` arg.

**Comment by dwalton76** [comment]
Turns out I do have a NXT Sound Sensor...will experiment with it some tonight

**Comment by dwalton76** [comment]
this
```
robot@evb[ev3dev-lang-python]# git diff
diff --git a/ev3dev2/sensor/lego.py b/ev3dev2/sensor/lego.py
index 781c748..13de8ed 100644
--- a/ev3dev2/sensor/lego.py
+++ b/ev3dev2/sensor/lego.py
@@ -30,6 +30,7 @@ if sys.version_info < (3,4):
 
 import time
 from ev3dev2.button import ButtonBase
+from ev3dev2.port import LegoPort
 from ev3dev2.sensor import Sensor
 
 
@@ -826,6 +827,8 @@ class SoundSensor(Sensor):
     )
 
     def __init__(self, address=None, name_pattern=SYSTEM_DEVICE_NAME_CONVENTION, name_exact=False, **kwargs):
+        if address:
+            LegoPort(address).set_device = 'lego-nxt-sound'
         super(SoundSensor, self).__init__(address, name_pattern, name_exact, driver_name='lego-nxt-sound', **kwargs)
 
     @property
robot@evb[ev3dev-lang-python]# 
```

plus running
```
robot@evb[ev3dev-lang-python]# cat utils/sound_sensor.py 
#!/usr/bin/env python3

"""
Used to test SoundSensor basics
"""

from ev3dev2.sensor import INPUT_1
from ev3dev2.sensor.lego import SoundSensor

import logging
import sys

# logging
logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s %(levelname)5s: %(message)s")
log = logging.getLogger(__name__)

ss = SoundSensor(INPUT_1)
log.info("%s: sound pressure %s" % (ss, ss.sound_pressure))
log.info("%s: sound pressure low %s" % (ss, ss.sound_pressure_low))
robot@evb[ev3dev-lang-python]# 
```

results in
```
robot@evb[ev3dev-lang-python]# ./utils/sound_sensor.py 
Traceback (most recent call last):
  File "./utils/sound_sensor.py", line 18, in <module>
    ss = SoundSensor(INPUT_1)
  File "/usr/local/lib/python3.5/dist-packages/python_ev3dev-0.8.0.post111-py3.5.egg/ev3dev2/sensor/lego.py", line 831, in __init__
  File "/usr/local/lib/python3.5/dist-packages/python_ev3dev-0.8.0.post111-py3.5.egg/ev3dev2/port.py", line 140, in set_device
  File "/usr/local/lib/python3.5/dist-packages/python_ev3dev-0.8.0.post111-py3.5.egg/ev3dev2/__init__.py", line 272, in set_attr_string
  File "/usr/local/lib/python3.5/dist-packages/python_ev3dev-0.8.0.post111-py3.5.egg/ev3dev2/__init__.py", line 235, in _set_attribute
  File "/usr/local/lib/python3.5/dist-packages/python_ev3dev-0.8.0.post111-py3.5.egg/ev3dev2/__init__.py", line 256, in _raise_friendly_access_error
  File "/usr/local/lib/python3.5/dist-packages/python_ev3dev-0.8.0.post111-py3.5.egg/ev3dev2/__init__.py", line 232, in _set_attribute
OSError: [Errno 95] Operation not supported
robot@evb[ev3dev-lang-python]# 
```

**Comment by dwalton76** [comment]
But so does @ddemidov 's suggestion which did work in early December
```
robot@evb[ev3dev-lang-python]# cat foo.py 
#!/usr/bin/env python3

import ev3dev2.auto as ev3
from time import sleep

p = ev3.LegoPort(ev3.INPUT_1)
p.set_device = 'lego-nxt-sound'
sleep(1)
s = ev3.SoundSensor()
robot@evb[ev3dev-lang-python]# 
robot@evb[ev3dev-lang-python]# ./foo.py 
Traceback (most recent call last):
  File "./foo.py", line 7, in <module>
    p.set_device = 'lego-nxt-sound'
  File "/home/robot/ev3dev-lang-python/ev3dev2/port.py", line 140, in set_device
    self._set_device = self.set_attr_string(self._set_device, 'set_device', value)
  File "/home/robot/ev3dev-lang-python/ev3dev2/__init__.py", line 272, in set_attr_string
    return self._set_attribute(attribute, name, value)
  File "/home/robot/ev3dev-lang-python/ev3dev2/__init__.py", line 235, in _set_attribute
    self._raise_friendly_access_error(ex, name)
  File "/home/robot/ev3dev-lang-python/ev3dev2/__init__.py", line 256, in _raise_friendly_access_error
    raise driver_error
  File "/home/robot/ev3dev-lang-python/ev3dev2/__init__.py", line 232, in _set_attribute
    attribute.write(value)
OSError: [Errno 95] Operation not supported
robot@evb[ev3dev-lang-python]# 
```

**Comment by WasabiFan** [comment]
@ensonic What's the status here -- can this be closed?

**Comment by dwalton76** [comment]
It had been 3 months of idle am closing this one. Please reopen if it is still an issue.
