### ISSUE TITLE
Can't install pygame

### ISSUE THREAD

**Issue by Niels1006** [ev3dev/ev3dev-lang-python#437]
Hey. 
I tried everything, I installed every possible package i could find on google, but I can't get the brick to install pygame.

Here's the Error for `pip install pygame==1.9.2`: (It throws the same error without this, but I heard this should work better)
```Downloading/unpacking pygame==1.9.2
  Downloading pygame-1.9.2.tar.gz (3.0MB): 3.0MB downloaded
-1.9.2  Running setup.py (path:/tmp/pip-build-5neXMR/pygame/setup.py) egg_info for package pygame


    WARNING, No "Setup" File Exists, Running "config.py"
    Using UNIX configuration...


    Hunting dependencies...
    SDL     : found 1.2.15
    FONT    : found
    IMAGE   : found
    MIXER   : found
    PNG     : found
    JPEG    : found
    SCRAP   : found
    PORTMIDI: found
    PORTTIME: found
    FREETYPE: found 2.5.2

    If you get compiler errors during install, doublecheck
    the compiler flags in the "Setup" file.


    Continuing With "setup.py"
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-5neXMR/pygame/setup.py", line 294, in <module>
        write_version_module(METADATA['version'], revision)
      File "/tmp/pip-build-5neXMR/pygame/setup.py", line 286, in write_version_module
        with open('version.py.in', 'r') as header_file:
    IOError: [Errno 2] No such file or directory: 'version.py.in'
    Complete output from command python setup.py egg_info:




WARNING, No "Setup" File Exists, Running "config.py"

Using UNIX configuration...





Hunting dependencies...

SDL     : found 1.2.15

FONT    : found

IMAGE   : found

MIXER   : found

PNG     : found

JPEG    : found

SCRAP   : found

PORTMIDI: found

PORTTIME: found

FREETYPE: found 2.5.2



If you get compiler errors during install, doublecheck

the compiler flags in the "Setup" file.





Continuing With "setup.py"

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-5neXMR/pygame/setup.py", line 294, in <module>

    write_version_module(METADATA['version'], revision)

  File "/tmp/pip-build-5neXMR/pygame/setup.py", line 286, in write_version_module

    with open('version.py.in', 'r') as header_file:

IOError: [Errno 2] No such file or directory: 'version.py.in'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-5neXMR/pygame
Storing debug log for failure in /root/.pip/pip.log
```

A reddit said, this will work: https://bitbucket.org/pygame/pygame/get/1.9.2.tar.gz

So I unzipped it tried to install it with ` python setup.py install`, but it throws this Error:

```running install
running bdist_egg
running egg_info
creating pygame.egg-info
writing pygame.egg-info/PKG-INFO
writing top-level names to pygame.egg-info/top_level.txt
writing dependency_links to pygame.egg-info/dependency_links.txt
writing manifest file 'pygame.egg-info/SOURCES.txt'
reading manifest file 'pygame.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching '*/CVS'
no previously-included directories found matching '*/*/CVS'
writing manifest file 'pygame.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv5tejl/egg
running install_lib
running build_py
creating build
creating build/lib.linux-armv5tejl-2.7
creating build/lib.linux-armv5tejl-2.7/pygame
copying lib/locals.py -> build/lib.linux-armv5tejl-2.7/pygame
copying lib/freetype.py -> build/lib.linux-armv5tejl-2.7/pygame
copying lib/_numpysurfarray.py -> build/lib.linux-armv5tejl-2.7/pygame
copying lib/sprite.py -> build/lib.linux-armv5tejl-2.7/pygame
copying lib/ftfont.py -> build/lib.linux-armv5tejl-2.7/pygame
copying lib/_camera_vidcapture.py -> build/lib.linux-armv5tejl-2.7/pygame
copying lib/_numpysndarray.py -> build/lib.linux-armv5tejl-2.7/pygame
copying lib/__init__.py -> build/lib.linux-armv5tejl-2.7/pygame
copying lib/surfarray.py -> build/lib.linux-armv5tejl-2.7/pygame
copying lib/pkgdata.py -> build/lib.linux-armv5tejl-2.7/pygame
copying lib/sndarray.py -> build/lib.linux-armv5tejl-2.7/pygame
copying lib/version.py -> build/lib.linux-armv5tejl-2.7/pygame
copying lib/sysfont.py -> build/lib.linux-armv5tejl-2.7/pygame
copying lib/_dummybackend.py -> build/lib.linux-armv5tejl-2.7/pygame
copying lib/_camera_opencv_highgui.py -> build/lib.linux-armv5tejl-2.7/pygame
copying lib/cursors.py -> build/lib.linux-armv5tejl-2.7/pygame
copying lib/compat.py -> build/lib.linux-armv5tejl-2.7/pygame
copying lib/macosx.py -> build/lib.linux-armv5tejl-2.7/pygame
copying lib/camera.py -> build/lib.linux-armv5tejl-2.7/pygame
copying lib/colordict.py -> build/lib.linux-armv5tejl-2.7/pygame
copying lib/midi.py -> build/lib.linux-armv5tejl-2.7/pygame
creating build/lib.linux-armv5tejl-2.7/pygame/gp2x
copying lib/gp2x/locals.py -> build/lib.linux-armv5tejl-2.7/pygame/gp2x
copying lib/gp2x/__init__.py -> build/lib.linux-armv5tejl-2.7/pygame/gp2x
copying lib/gp2x/constants.py -> build/lib.linux-armv5tejl-2.7/pygame/gp2x
creating build/lib.linux-armv5tejl-2.7/pygame/threads
copying lib/threads/Py25Queue.py -> build/lib.linux-armv5tejl-2.7/pygame/threads
copying lib/threads/__init__.py -> build/lib.linux-armv5tejl-2.7/pygame/threads
creating build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/test_test_.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/camera_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/time_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/font_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/display_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/rect_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/image_tags.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/cdrom_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/mixer_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/scrap_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/cursors_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/draw_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/mouse_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/mixer_music_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/sndarray_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/scrap_tags.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/__init__.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/transform_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/font_tags.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/rwobject_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/mask_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/image_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/gfxdraw_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/color_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/mixer_tags.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/freetype_tags.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/key_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/cdrom_tags.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/overlay_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/joystick_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/mixer_music_tags.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/ftfont_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/surflock_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/surface_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/threads_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/midi_tags.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/compat_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/base_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/math_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/surfarray_tags.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/freetype_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/event_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/pixelcopy_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/imageext_tags.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/sndarray_tags.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/ftfont_tags.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/image__save_gl_surface_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/__main__.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/sprite_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/bufferproxy_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/midi_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/sysfont_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/pixelarray_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/fastevent_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/surfarray_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/imageext_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
copying test/blit_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests
creating build/lib.linux-armv5tejl-2.7/pygame/tests/test_utils
copying test/test_utils/test_runner.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/test_utils
copying test/test_utils/endian.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/test_utils
copying test/test_utils/__init__.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/test_utils
copying test/test_utils/buftools.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/test_utils
copying test/test_utils/run_tests.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/test_utils
copying test/test_utils/async_sub.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/test_utils
copying test/test_utils/png.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/test_utils
copying test/test_utils/test_machinery.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/test_utils
copying test/test_utils/arrinter.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/test_utils
creating build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests
copying test/run_tests__tests/__init__.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests
copying test/run_tests__tests/run_tests__test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests
creating build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/all_ok
copying test/run_tests__tests/all_ok/fake_2_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/all_ok
copying test/run_tests__tests/all_ok/fake_3_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/all_ok
copying test/run_tests__tests/all_ok/zero_tests_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/all_ok
copying test/run_tests__tests/all_ok/fake_5_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/all_ok
copying test/run_tests__tests/all_ok/no_assertions__ret_code_of_1__test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/all_ok
copying test/run_tests__tests/all_ok/__init__.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/all_ok
copying test/run_tests__tests/all_ok/fake_4_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/all_ok
copying test/run_tests__tests/all_ok/fake_6_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/all_ok
creating build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/failures1
copying test/run_tests__tests/failures1/fake_2_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/failures1
copying test/run_tests__tests/failures1/fake_3_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/failures1
copying test/run_tests__tests/failures1/__init__.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/failures1
copying test/run_tests__tests/failures1/fake_4_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/failures1
creating build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/incomplete
copying test/run_tests__tests/incomplete/fake_2_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/incomplete
copying test/run_tests__tests/incomplete/fake_3_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/incomplete
copying test/run_tests__tests/incomplete/__init__.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/incomplete
creating build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/infinite_loop
copying test/run_tests__tests/infinite_loop/fake_2_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/infinite_loop
copying test/run_tests__tests/infinite_loop/__init__.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/infinite_loop
copying test/run_tests__tests/infinite_loop/fake_1_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/infinite_loop
creating build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/print_stderr
copying test/run_tests__tests/print_stderr/fake_2_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/print_stderr
copying test/run_tests__tests/print_stderr/fake_3_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/print_stderr
copying test/run_tests__tests/print_stderr/__init__.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/print_stderr
copying test/run_tests__tests/print_stderr/fake_4_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/print_stderr
creating build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/print_stdout
copying test/run_tests__tests/print_stdout/fake_2_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/print_stdout
copying test/run_tests__tests/print_stdout/fake_3_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/print_stdout
copying test/run_tests__tests/print_stdout/__init__.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/print_stdout
copying test/run_tests__tests/print_stdout/fake_4_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/print_stdout
creating build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/incomplete_todo
copying test/run_tests__tests/incomplete_todo/fake_2_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/incomplete_todo
copying test/run_tests__tests/incomplete_todo/fake_3_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/incomplete_todo
copying test/run_tests__tests/incomplete_todo/__init__.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/incomplete_todo
creating build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/exclude
copying test/run_tests__tests/exclude/fake_2_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/exclude
copying test/run_tests__tests/exclude/magic_tag_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/exclude
copying test/run_tests__tests/exclude/__init__.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/exclude
copying test/run_tests__tests/exclude/invisible_tag_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/exclude
creating build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/timeout
copying test/run_tests__tests/timeout/fake_2_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/timeout
copying test/run_tests__tests/timeout/__init__.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/timeout
copying test/run_tests__tests/timeout/sleep_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/timeout
creating build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/everything
copying test/run_tests__tests/everything/fake_2_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/everything
copying test/run_tests__tests/everything/magic_tag_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/everything
copying test/run_tests__tests/everything/__init__.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/everything
copying test/run_tests__tests/everything/sleep_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/everything
copying test/run_tests__tests/everything/incomplete_todo_test.py -> build/lib.linux-armv5tejl-2.7/pygame/tests/run_tests__tests/everything
creating build/lib.linux-armv5tejl-2.7/pygame/docs
copying docs/__init__.py -> build/lib.linux-armv5tejl-2.7/pygame/docs
copying docs/__main__.py -> build/lib.linux-armv5tejl-2.7/pygame/docs
creating build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/arraydemo.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/sound.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/aliens.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/moveit.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/testsprite.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/playmus.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/blit_blends.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/eventlist.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/fonty.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/pixelarray.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/sound_array_demos.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/mask.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/__init__.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/scrap_clipboard.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/glcube.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/fastevents.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/vgrade.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/freetype_misc.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/scaletest.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/stars.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/scroll.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/headless_no_windows_needed.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/cursors.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/liquid.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/aacircle.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/overlay.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/camera.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/blend_fill.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/chimp.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/prevent_display_stretching.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/oldalien.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
copying examples/midi.py -> build/lib.linux-armv5tejl-2.7/pygame/examples
running build_ext
building 'pygame.imageext' extension
creating build/temp.linux-armv5tejl-2.7
creating build/temp.linux-armv5tejl-2.7/src
arm-linux-gnueabi-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -D_REENTRANT -DENABLE_NEWBUF=1 -I/usr/X11R6/include -I/usr/include/SDL -I/usr/include/SDL -I/usr/include -I/usr/include -I/usr/include/python2.7 -c src/imageext.c -o build/temp.linux-armv5tejl-2.7/src/imageext.o
In file included from src/pygame.h:32:0,
                 from src/imageext.c:49:
src/_pygame.h:80:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
error: command 'arm-linux-gnueabi-gcc' failed with exit status 1
```

Would be great if someone knows a solution, thank you :)

**Comment by WasabiFan** [comment]
Can you please post the output of `ev3dev-sysinfo -m`?

**Comment by Niels1006** [comment]
Yeah, I totally forgot it, sorry!
**System info (from `ev3dev-sysinfo`)**
```
Image file:         ev3dev-jessie-ev3-generic-2017-09-14
Kernel version:     4.4.87-22-ev3dev-ev3
Board:              LEGO MINDSTORMS EV3 Programmable Brick
Revision:           0006
Brickman:           0.8.1
ev3devKit:          0.4.3
```

**Comment by WasabiFan** [comment]
I'll take a look at this later today. Out of curiosity, _why_ are you trying to install pygame on an EV3? :laughing:

**Comment by Niels1006** [comment]
To control it with my ds4 controller ^^. I did this already like one and a half year ago

**Comment by dlech** [comment]
Don't use `pip`, use the debian package.

    sudo apt update
    sudo apt install python3-pygame

**Comment by Niels1006** [comment]
I tried it already, but i got an error with this too. I'll flash the latest ev3dev image now and try it again.

**Comment by Niels1006** [comment]
Mhh, seems like the package has another name or I am dumb, I think its the last.
```
robot@ev3dev:~$ sudo apt install python3-pygame
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package python3-pygame is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-pygame' has no installation candidate
```

**Comment by dlech** [comment]
I guess there isn't a python3 version on jessie

    sudo apt install python-pygame

**Comment by Niels1006** [comment]
ev3dev works with python 2.7 too, right?

**Comment by dlech** [comment]
nope, but there is ev3dev-stretch

**Comment by WasabiFan** [comment]
The goal here is to install pygame for use with the ev3dev Python library. While @Niels1006 certainly can switch to Stretch (the next version of ev3dev, not the currently recommended version for general use but stable) if they want to, it still seems reasonable to me to try getting pygame installed via `pip` or another means on Jessie.

Alternately, if it's just gamepad input support that you're looking for, I'm sure there are other smaller Python libraries which provide that individually.

**Comment by Niels1006** [comment]
Well, i try another library, but i guess pygame is the fastest 🤔 . But `evdev` should be fast too, so im gonna test it ^^. Thank you for your help btw 💯 .
