### ISSUE TITLE
still can't connect sensors to my brickpi with ev3dev.

### ISSUE THREAD

**Issue by coffeedood** [ev3dev/ev3dev-lang-python#555]
it always seems to return with Exception: LegoPort(serial0-0:S1) is not connected.  Any help?

>>> import ev3dev.brickpi as ev3
>>> 
>>> p = ev3.LegoPort(ev3.INPUT_1)
>>> p.mode = "nxt-analog"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 3062, in mode
    self._mode = self.set_attr_string(self._mode, 'mode', value)
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 229, in set_attr_string
    return self._set_attribute(attribute, name, value)
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 216, in _set_attribute
    raise Exception("%s is not connected" % self)
Exception: LegoPort(serial0-0:S1) is not connected
>>> p.set_device = "lego-nxt-touch"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 3077, in set_device
    self._set_device = self.set_attr_string(self._set_device, 'set_device', value)
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 229, in set_attr_string
    return self._set_attribute(attribute, name, value)
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 216, in _set_attribute
    raise Exception("%s is not connected" % self)
Exception: LegoPort(serial0-0:S1) is not connected
>>> from ev3dev.brickpi3 import *
>>> import ev3dev.brickpi as ev3
>>> p = ev3.LegoPort(ev3.INPUT_1)
>>> p.set_device = "lego-nxt-touch"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 3077, in set_device
    self._set_device = self.set_attr_string(self._set_device, 'set_device', value)
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 229, in set_attr_string
    return self._set_attribute(attribute, name, value)
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 216, in _set_attribute
    raise Exception("%s is not connected" % self)
Exception: LegoPort(serial0-0:S1) is not connected

**Comment by dlech** [comment]
Are you using BrickPi or BrickPi3?

**Comment by coffeedood** [comment]
brickpi3

**Comment by dlech** [comment]
> import ev3dev.brickpi as ev3

So this needs to be

    import ev3dev.brickpi3 as ev3

**Comment by coffeedood** [comment]
still getting the same error.

>>> import ev3dev.brickpi3 as ev3
>>> p = ev3.LegoPort(ev3.INPUT_1)
>>> p.mode = "nxt-analog"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 3062, in mode
    self._mode = self.set_attr_string(self._mode, 'mode', value)
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 229, in set_attr_string
    return self._set_attribute(attribute, name, value)
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 216, in _set_attribute
    raise Exception("%s is not connected" % self)
Exception: LegoPort(spi0.1:S1) is not connected

**Comment by dlech** [comment]
> Exception: LegoPort(**serial0-0:S1**) is not connected

> Exception: LegoPort(**spi0.1:S1**) is not connected

not quite the same

Did you enable the BrickPi3 in `config.txt`? Does the yellow light on the BrickPi3 flash or is it on steady? Are there any messages about `brickpi3` in the output of the `dmesg` command?

**Comment by coffeedood** [comment]
I believe I enabled the BrickPi3 in the config.txt.  The yellow light flashes slowly.  This is what I get when I type in dmesg.

```
robot@ev3dev:~$ dmesg
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.14.59-ev3dev-2.2.2-rpi2 (david@freyr) (gcc version 6.4.1 20171012 (Linaro GCC 6.4-2017.11)) #1 SMP Mon Aug 6 16:17:02 CDT 2018
[    0.000000] CPU: ARMv7 Processor [410fd034] revision 4 (ARMv7), cr=10c5383d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt: Machine model: Raspberry Pi 3 Model B Rev 1.2
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] cma: Reserved 8 MiB at 0x3ac00000
[    0.000000] On node 0 totalpages: 242688
[    0.000000] free_area_init_node: node 0, pgdat 80c85740, node_mem_map ba39f000
[    0.000000]   Normal zone: 2133 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 242688 pages, LIFO batch:31
[    0.000000] percpu: Embedded 17 pages/cpu @ba348000 s38604 r8192 d22836 u69632
[    0.000000] pcpu-alloc: s38604 r8192 d22836 u69632 alloc=17*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3 
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 240555
[    0.000000] Kernel command line: 8250.nr_uarts=0 bcm2708_fb.fbwidth=656 bcm2708_fb.fbheight=416 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  dwc_otg.lpm_enable=0 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait consoleblank=0
[    0.000000] PID hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Dentry cache hash table entries: 131072 (order: 7, 524288 bytes)
[    0.000000] Inode-cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Memory: 940220K/970752K available (7168K kernel code, 577K rwdata, 2232K rodata, 1024K init, 710K bss, 22340K reserved, 8192K cma-reserved)
[    0.000000] Virtual kernel memory layout:
                   vector  : 0xffff0000 - 0xffff1000   (   4 kB)
                   fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
                   vmalloc : 0xbb800000 - 0xff800000   (1088 MB)
                   lowmem  : 0x80000000 - 0xbb400000   ( 948 MB)
                   modules : 0x7f000000 - 0x80000000   (  16 MB)
                     .text : 0x80008000 - 0x80800000   (8160 kB)
                     .init : 0x80b00000 - 0x80c00000   (1024 kB)
                     .data : 0x80c00000 - 0x80c9075c   ( 578 kB)
                      .bss : 0x80c98294 - 0x80d49d64   ( 711 kB)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] ftrace: allocating 26413 entries in 78 pages
[    0.000000] Hierarchical RCU implementation.
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] arch_timer: cp15 timer(s) running at 19.20MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x46d987e47, max_idle_ns: 440795202767 ns
[    0.000006] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 4398046511078ns
[    0.000020] Switching to timer-based delay loop, resolution 52ns
[    0.000265] Console: colour dummy device 80x30
[    0.000783] console [tty1] enabled
[    0.000816] Calibrating delay loop (skipped), value calculated using timer frequency.. 38.40 BogoMIPS (lpj=192000)
[    0.000856] pid_max: default: 32768 minimum: 301
[    0.001169] Mount-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.001201] Mountpoint-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.002150] Disabling memory control group subsystem
[    0.002241] CPU: Testing write buffer coherency: ok
[    0.002650] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.003035] Setting up static identity map for 0x100000 - 0x10003c
[    0.003164] Hierarchical SRCU implementation.
[    0.003819] smp: Bringing up secondary CPUs ...
[    0.004511] CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
[    0.005247] CPU2: thread -1, cpu 2, socket 0, mpidr 80000002
[    0.005969] CPU3: thread -1, cpu 3, socket 0, mpidr 80000003
[    0.006070] smp: Brought up 1 node, 4 CPUs
[    0.006140] SMP: Total of 4 processors activated (153.60 BogoMIPS).
[    0.006161] CPU: All CPU(s) started in HYP mode.
[    0.006178] CPU: Virtualization extensions available.
[    0.007012] devtmpfs: initialized
[    0.016798] random: get_random_u32 called from bucket_table_alloc+0x100/0x254 with crng_init=0
[    0.017418] VFP support v0.3: implementor 41 architecture 3 part 40 variant 3 rev 4
[    0.017660] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.017703] futex hash table entries: 1024 (order: 4, 65536 bytes)
[    0.018288] pinctrl core: initialized pinctrl subsystem
[    0.019032] NET: Registered protocol family 16
[    0.021542] DMA: preallocated 1024 KiB pool for atomic coherent allocations
[    0.026158] hw-breakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint registers.
[    0.026190] hw-breakpoint: maximum watchpoint size is 8 bytes.
[    0.026386] Serial: AMBA PL011 UART driver
[    0.028007] bcm2835-mbox 3f00b880.mailbox: mailbox enabled
[    0.028467] uart-pl011 3f201000.serial: could not find pctldev for node /soc/gpio@7e200000/uart0_pins, deferring probe
[    0.059528] bcm2835-dma 3f007000.dma: DMA legacy API manager at bb813000, dmachans=0x1
[    0.060975] SCSI subsystem initialized
[    0.061210] usbcore: registered new interface driver usbfs
[    0.061277] usbcore: registered new interface driver hub
[    0.061376] usbcore: registered new device driver usb
[    0.070159] raspberrypi-firmware soc:firmware: Attached to firmware from 2018-04-09 17:46
[    0.071406] clocksource: Switched to clocksource arch_sys_counter
[    0.145668] VFS: Disk quotas dquot_6.6.0
[    0.145789] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.146009] FS-Cache: Loaded
[    0.146223] CacheFiles: Loaded
[    0.154979] NET: Registered protocol family 2
[    0.155678] TCP established hash table entries: 8192 (order: 3, 32768 bytes)
[    0.155809] TCP bind hash table entries: 8192 (order: 4, 65536 bytes)
[    0.156011] TCP: Hash tables configured (established 8192 bind 8192)
[    0.156153] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    0.156214] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    0.156455] NET: Registered protocol family 1
[    0.156912] RPC: Registered named UNIX socket transport module.
[    0.156936] RPC: Registered udp transport module.
[    0.156955] RPC: Registered tcp transport module.
[    0.156974] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.158337] hw perfevents: enabled with armv7_cortex_a7 PMU driver, 7 counters available
[    0.161040] workingset: timestamp_bits=14 max_order=18 bucket_order=4
[    0.168905] FS-Cache: Netfs 'nfs' registered for caching
[    0.169515] NFS: Registering the id_resolver key type
[    0.169561] Key type id_resolver registered
[    0.169581] Key type id_legacy registered
[    0.169609] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    0.171483] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 251)
[    0.171625] io scheduler noop registered
[    0.171647] io scheduler deadline registered (default)
[    0.171927] io scheduler cfq registered
[    0.171948] io scheduler mq-deadline registered
[    0.171968] io scheduler kyber registered
[    0.174555] BCM2708FB: allocated DMA memory fad10000
[    0.174597] BCM2708FB: allocated DMA channel 0 @ bb813000
[    0.182337] Console: switching to colour frame buffer device 82x26
[    0.189546] bcm2835-rng 3f104000.rng: hwrng registered
[    0.191665] vc-mem: phys_addr:0x00000000 mem_base=0x3ec00000 mem_size:0x40000000(1024 MiB)
[    0.196030] vc-sm: Videocore shared memory driver
[    0.198246] gpiomem-bcm2835 3f200000.gpiomem: Initialised: Registers at 0x3f200000
[    0.211573] brd: module loaded
[    0.222069] loop: module loaded
[    0.224005] Loading iSCSI transport class v2.0-870.
[    0.226801] libphy: Fixed MDIO Bus: probed
[    0.228823] usbcore: registered new interface driver lan78xx
[    0.230800] usbcore: registered new interface driver smsc95xx
[    0.232661] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    0.262340] dwc_otg 3f980000.usb: base=0xf0980000
[    0.464381] Core Release: 2.80a
[    0.466219] Setting default values for core params
[    0.468126] Finished setting default values for core params
[    0.670306] Using Buffer DMA mode
[    0.672243] Periodic Transfer Interrupt Enhancement - disabled
[    0.674262] Multiprocessor Interrupt Enhancement - disabled
[    0.676267] OTG VER PARAM: 0, OTG VER FLAG: 0
[    0.678242] Dedicated Tx FIFOs mode
[    0.680521] WARN::dwc_otg_hcd_init:1046: FIQ DMA bounce buffers: virt = 0xbad04000 dma = 0xfad04000 len=9024
[    0.684411] FIQ FSM acceleration enabled for :
               Non-periodic Split Transactions
               Periodic Split Transactions
               High-Speed Isochronous Endpoints
               Interrupt/Control Split Transaction hack enabled
[    0.693617] dwc_otg: Microframe scheduler enabled
[    0.693672] WARN::hcd_init_fiq:459: FIQ on core 1 at 0x806320d0
[    0.695588] WARN::hcd_init_fiq:460: FIQ ASM at 0x8063242c length 36
[    0.697473] WARN::hcd_init_fiq:486: MPHI regs_base at 0xf0006000
[    0.699432] dwc_otg 3f980000.usb: DWC OTG Controller
[    0.701362] dwc_otg 3f980000.usb: new USB bus registered, assigned bus number 1
[    0.703360] dwc_otg 3f980000.usb: irq 62, io mem 0x00000000
[    0.705327] Init: Port Power? op_state=1
[    0.707229] Init: Power Port (0)
[    0.709265] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[    0.711216] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.713174] usb usb1: Product: DWC OTG Controller
[    0.715075] usb usb1: Manufacturer: Linux 4.14.59-ev3dev-2.2.2-rpi2 dwc_otg_hcd
[    0.717045] usb usb1: SerialNumber: 3f980000.usb
[    0.719579] hub 1-0:1.0: USB hub found
[    0.721517] hub 1-0:1.0: 1 port detected
[    0.723776] dwc_otg: FIQ enabled
[    0.723781] dwc_otg: NAK holdoff enabled
[    0.723786] dwc_otg: FIQ split-transaction FSM enabled
[    0.723796] Module dwc_common_port init
[    0.724025] usbcore: registered new interface driver usb-storage
[    0.726033] mousedev: PS/2 mouse device common for all mice
[    0.727899] i2c /dev entries driver
[    0.729839] IR NEC protocol handler initialized
[    0.731740] IR RC5(x/sz) protocol handler initialized
[    0.733626] IR RC6 protocol handler initialized
[    0.735472] IR JVC protocol handler initialized
[    0.737271] IR Sony protocol handler initialized
[    0.739072] IR SANYO protocol handler initialized
[    0.740842] IR Sharp protocol handler initialized
[    0.742558] IR MCE Keyboard/mouse protocol handler initialized
[    0.744293] IR XMP protocol handler initialized
[    0.746663] bcm2835-wdt 3f100000.watchdog: Broadcom BCM2835 watchdog timer
[    0.748749] bcm2835-cpufreq: min=600000 max=1200000
[    0.750864] sdhci: Secure Digital Host Controller Interface driver
[    0.752708] sdhci: Copyright(c) Pierre Ossman
[    0.754810] mmc-bcm2835 3f300000.mmc: could not get clk, deferring probe
[    0.756940] sdhost-bcm2835 3f202000.mmc: could not get clk, deferring probe
[    0.758868] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.762121] ledtrig-cpu: registered to indicate activity on CPUs
[    0.764215] hidraw: raw HID events driver (C) Jiri Kosina
[    0.766298] usbcore: registered new interface driver usbhid
[    0.768204] usbhid: USB HID core driver
[    0.770740] vchiq: vchiq_init_state: slot_zero = bad80000, is_master = 0
[    0.774071] [vc_sm_connected_init]: start
[    0.782843] [vc_sm_connected_init]: end - returning 0
[    0.785348] Initializing XFRM netlink socket
[    0.787356] NET: Registered protocol family 17
[    0.789446] Key type dns_resolver registered
[    0.791812] Registering SWP/SWPB emulation handler
[    0.794454] registered taskstats version 1
[    0.802190] uart-pl011 3f201000.serial: cts_event_workaround enabled
[    0.804357] 3f201000.serial: ttyAMA0 at MMIO 0x3f201000 (irq = 87, base_baud = 0) is a PL011 rev2
[    0.810418] mmc-bcm2835 3f300000.mmc: mmc_debug:0 mmc_debug2:0
[    0.812597] mmc-bcm2835 3f300000.mmc: DMA channel allocated
[    0.872036] sdhost: log_buf @ bad07000 (fad07000)
[    0.908280] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
[    0.911886] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.915375] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.920005] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
[    0.941502] Indeed it is in host mode hprt0 = 00021501
[    1.003310] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    1.006150] of_cfs_init
[    1.007995] of_cfs_init: OK
[    1.010142] Waiting for root device /dev/mmcblk0p2...
[    1.020798] random: fast init done
[    1.078584] mmc0: host does not support reading read-only switch, assuming write-enable
[    1.084943] mmc0: new high speed SDHC card at address 0001
[    1.087308] mmcblk0: mmc0:0001 00000 7.44 GiB
[    1.090963]  mmcblk0: p1 p2
[    1.112399] mmc1: new high speed SDIO card at address 0001
[    1.115032] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    1.118627] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    1.129579] devtmpfs: mounted
[    1.134679] Freeing unused kernel memory: 1024K
[    1.151437] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    1.153882] Indeed it is in host mode hprt0 = 00001101
[    1.391726] usb 1-1: New USB device found, idVendor=0424, idProduct=9514
[    1.393976] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.396846] hub 1-1:1.0: USB hub found
[    1.399089] hub 1-1:1.0: 5 ports detected
[    1.510779] systemd[1]: System time before build time, advancing clock.
[    1.617343] NET: Registered protocol family 10
[    1.620845] Segment Routing with IPv6
[    1.641553] ip_tables: (C) 2000-2006 Netfilter Core Team
[    1.657524] random: systemd: uninitialized urandom read (16 bytes read)
[    1.665235] systemd[1]: systemd 232 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
[    1.672699] systemd[1]: Detected architecture arm.
[    1.684668] systemd[1]: Set hostname to <ev3dev>.
[    1.710272] random: systemd: uninitialized urandom read (16 bytes read)
[    1.731504] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    1.741139] random: systemd-cryptse: uninitialized urandom read (16 bytes read)
[    1.861782] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00
[    1.864037] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.868945] smsc95xx v1.0.6
[    1.974945] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-3f980000.usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:73:23:f5
[    2.071461] usb 1-1.2: new high-speed USB device number 4 using dwc_otg
[    2.092545] systemd[1]: openrobertalab.service: Cannot add dependency job, ignoring: Unit openrobertalab.service is masked.
[    2.102607] systemd[1]: Listening on udev Kernel Socket.
[    2.108925] systemd[1]: Created slice System Slice.
[    2.116761] systemd[1]: Mounting Debug File System...
[    2.123541] systemd[1]: Created slice system-console\x2drunner.slice.
[    2.130751] systemd[1]: Created slice system-getty.slice.
[    2.139773] systemd[1]: Mounting RPC Pipe File System...
[    2.202927] usb 1-1.2: New USB device found, idVendor=0bda, idProduct=8176
[    2.205513] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    2.208302] usb 1-1.2: Product: 802.11n WLAN Adapter
[    2.208310] usb 1-1.2: Manufacturer: Realtek
[    2.208317] usb 1-1.2: SerialNumber: 00e04c000001
[    2.437676] EXT4-fs (mmcblk0p2): re-mounted. Opts: errors=remount-ro
[    2.533578] systemd-journald[106]: Received request to flush runtime journal from PID 1
[    2.547555] systemd-journald[106]: File /var/log/journal/7974e7546ffc4b1cbc7fb8e7dbb4d415/system.journal corrupted or uncleanly shut down, renaming and replacing.
[    3.140423] rtl8192cu: Chip version 0x10
[    3.215543] rtl8192cu: Board Type 0
[    3.218647] rtl_usb: rx_max_size 15360, rx_urb_num 8, in_ep 1
[    3.221952] rtl8192cu: Loading firmware rtlwifi/rtl8192cufw_TMSC.bin
[    3.244633] ieee80211 phy0: Selected rate control algorithm 'rtl_rc'
[    3.245817] usbcore: registered new interface driver rtl8192cu
[    3.292875] Error: Driver 'rtl8192cu' is already registered, aborting...
[    3.432075] Error: Driver 'rtl8192cu' is already registered, aborting...
[    3.657404] Error: Driver 'rtl8192cu' is already registered, aborting...
[    3.683643] smsc95xx 1-1.1:1.0 enxb827eb7323f5: renamed from eth0
[    3.759496] brcmfmac: F1 signature read @0x18000000=0x1541a9a6
[    3.765863] brcmfmac: brcmf_fw_map_chip_to_name: using brcm/brcmfmac43430-sdio.bin for chip 0x00a9a6(43430) rev 0x000001
[    3.766863] Error: Driver 'rtl8192cu' is already registered, aborting...
[    3.791718] usbcore: registered new interface driver brcmfmac
[    3.912098] rtl8192cu 1-1.2:1.0 wlxe84e064ba801: renamed from wlan0
[    4.014566] brcmfmac: brcmf_c_preinit_dcmds: Firmware version = wl0: Oct 23 2017 03:55:53 version 7.45.98.38 (r674442 CY) FWID 01-e58d219f
[    4.028116] brcmfmac: brcmf_c_preinit_dcmds: CLM version = API: 12.2 Data: 7.11.15 Compiler: 1.24.2 ClmImport: 1.24.1 Creation: 2014-05-26 10:53:55 Inc Data: 9.10.39 Inc Compiler: 1.29.4 Inc ClmImport: 1.36.3 Creation: 2017-10-23 03:47:14 
[    4.080149] random: crng init done
[    4.083805] random: 7 urandom warning(s) missed due to ratelimiting
[    4.437068] uart-pl011 3f201000.serial: no DMA platform data
[    4.564969] Bluetooth: Core ver 2.22
[    4.568274] NET: Registered protocol family 31
[    4.571817] Bluetooth: HCI device and connection manager initialized
[    4.575295] Bluetooth: HCI socket layer initialized
[    4.579168] Bluetooth: L2CAP socket layer initialized
[    4.582684] Bluetooth: SCO socket layer initialized
[    4.609756] Bluetooth: HCI UART driver ver 2.3
[    4.612980] Bluetooth: HCI UART protocol H4 registered
[    4.616030] Bluetooth: HCI UART protocol Three-wire (H5) registered
[    4.619393] Bluetooth: HCI UART protocol Broadcom registered
[    4.883171] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[    4.883176] Bluetooth: BNEP filters: protocol multicast
[    4.883196] Bluetooth: BNEP socket layer initialized
[    5.297917] nf_conntrack version 0.5.0 (15360 buckets, 61440 max)
[    5.755199] smsc95xx 1-1.1:1.0 enxb827eb7323f5: hardware isn't capable of remote wakeup
[    5.755575] IPv6: ADDRCONF(NETDEV_UP): enxb827eb7323f5: link is not ready
[    5.834426] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[    5.834462] brcmfmac: power management disabled
[    5.837050] rtl8192cu: MAC auto ON okay!
[    5.866166] rtl8192cu: Tx queue select: 0x05
[    6.960401] IPv6: ADDRCONF(NETDEV_UP): wlxe84e064ba801: link is not ready
[    7.524677] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
robot@ev3dev:~$ 
```

**Comment by dlech** [comment]
Sounds like it is not enabled. The light should not be flashing and you should see something like

```
[    6.930429] brickpi3 spi0.1: Address: 1
[    6.932868] brickpi3 spi0.1: Mfg: Dexter Industries
[    6.955602] brickpi3 spi0.1: Board: BrickPi3
[    6.963820] brickpi3 spi0.1: HW: 3.2.1
[    6.970102] brickpi3 spi0.1: FW: 1.4.6
[    7.007287] brickpi3 spi0.1: ID: FAD3CABB504B5354392E314BFF0F2C38
```

**Comment by WasabiFan** [comment]
Is there still an issue to be fixed here or can this be closed?
